### ISSUE TITLE
medusaup

### ISSUE THREAD

**Issue by aviggiano** [crytic/medusa#352] opened 2024-04-19 17:40 UTC
As a beta tester, I would like to always use the latest version of medusa.

It would be nice to have a `medusaup` command similar to `foundryup` so that it can compile from the `master` branch

**Comment by 0xalpharush** [comment] 2024-04-19 17:41
This is a duplicate of https://github.com/crytic/medusa/issues/205

What is the blocker on https://github.com/crytic/medusa/pull/224 @anishnaik ?

**Closed as completed** 2024-04-19 17:53 UTC

**Comment by Xenomega** [comment] 2024-04-19 18:19
@0xalpharush We've discussed, the fix likely won't be creating a `medusaup` command, but fixing `go get` (so you can use the normal Go flow to pull the tool).

We can't use `go get` now because we use a `replaces` directive in `medusa-geth`, and `go get` does not respect `replaces` directives unless it's at the top level (e.g. `medusa`, if that's what you're 'getting', rather than `medusa-geth`, a dependency). 

This is only a problem because we tried to maintain the original `github.com/ethereum/go-ethereum` module path in `medusa-geth`, and use a `replaces` directive to redirect it. We thought this would be nice, but caught on to the `go get` caveat later and never revisited it.

The fix will look like this:
- All future forks of `medusa-geth` will simply apply our patchset as normal, and we'll just have one additional step: another commit we'll make atop all other changes, where we'll refactor all instances of `github.com/ethereum/go-ethereum` to `github.com/crytic/medusa-geth`.
- A one-time update made to `medusa` after we update `medusa-geth`, simply updating all imported module paths to the new ones.

That will let us use `go get` and will be required for some other planned features.
